package com.hospital

/**
 * Created by dhanendra on 11/3/17.
 */
enum Services {
    PHYSIOTHERAPY, OCCUPATIONAL_THERAPY, NUTRITION_THERAPY, NURSING_SERVICES, ATTENDANT, COOPERATE_PLANS, MEDICAL_TOURISM, DOCTOR_CONSULTATION, OTHER
}